image: python:3.11

stages:
  - format
  - lint
  - type_check
  - test
  - coverage

before_script:
  - pip install ruff mypy pytest pytest-cov

format:
  stage: format
  script:
    - ruff format --check .

lint:
  stage: lint
  script:
    - ruff check .

type_check:
  stage: type_check
  script:
    - mypy .

test:
  stage: test
  script:
    - pytest

coverage:
  stage: coverage
  script:
    - pytest --cov=. --cov-report=term