workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - format
  - lint
  - type_check
  - test

image: python:3.11

default:
  tags:
    - ubuntu-wsl-runner
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements-dev.txt || true